### PR TITLE
modified the library to be easier to include outside of Arduino.

### PR DESCRIPTION
**Pull request by hoeken**
I was having issues including this library in a project that has a pretty complex include tree, so I modified it to be a bit more library like.  I'll be using it in the upcoming version of ArduinoMongoose wrapper.

### CODE REVIEW

**Comment by rzeldent** [comment]
Hi Zach,

Thank you very much for your interest in the library; it is a small and handy utility function and please use it...

I have some doubts because the .h file can be included and the checking functions can (should) be inlined.
Now a call to check is required and uses the stack...
The case to determine the strings will also be present, and takes space if you do not use it (or only during debugging). However, it might be that a smart compiler will remove this...

What do you think?

**Comment by hoeken** [comment]
Hi Rene,

Honestly, I am not an expert on the nuances of inline vs fully defined and all that good stuff.  I was just having issues during linking with the library as it was, so I modified it to work for me.  I am using it on an esp32 board, so I am not bothered by a little bit larger program size or even a bit higher memory usage.

It would be nice if you accepted the PR, but no worries if you don't want to.

**Comment by rzeldent** [comment]
Hi Zach,

I will accept the PR. It looks nice and has a cleaner separation between header and code. The point is to have a library that works and is easy to use. I think your PR helps in that!

I was wondering what your problems were. It might be caused by the compiler not accepting the #pragma once?

**Comment by hoeken** [comment]
Thanks, I appreciate it.

I'm not sure exactly what the problem was.  The program compiled, but threw multiple errors during the linking stage that various functions from this library were redefined.  I'm using it in this project: https://github.com/hoeken/yarrboard-firmware  My dev environment is VSCode + platformio + arduino framework.

I think it came down to the file being included multiple times and the compiler not liking that.  The new way is all good though.

**Pull request merged**
